#
# /etc/doas.conf
#

permit persist :sudo

permit nopass :adm as root cmd /bin/dmesg
permit nopass :adm as root cmd /bin/apt-get args update
permit nopass :adm as root cmd /bin/apt-get args -y dist-upgrade
permit nopass :adm as root cmd /bin/apt-get args -y autoremove --purge
permit nopass :adm as root cmd /bin/apt-get args autoclean
permit nopass :adm as root cmd /bin/apt-get args clean
permit nopass :adm as root cmd /sbin/dhclient

# vagrant
permit nopass :libvirt as root cmd /bin/chown args 0:0 /tmp/vagrant-exports
permit nopass :libvirt as root cmd /bin/mv args -f /tmp/vagrant-exports /etc/exports
permit nopass :libvirt as root cmd /etc/init.d/nfs-kernel-server args start
permit nopass :libvirt as root cmd /etc/init.d/nfs-kernel-server args stop
permit nopass :libvirt as root cmd /etc/init.d/nfs-kernel-server args reload
permit nopass :libvirt as root cmd /etc/init.d/nfs-kernel-server args force-reload
permit nopass :libvirt as root cmd /sbin/exportfs args -ar
